---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-extensions-volume
  labels:
    app: sonarqube
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ubuntu/sonar/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-extensions-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: manual
  selector:
    matchLabels:
      app: sonar-extensions-volume
