apiVersion: v1
kind: Service
metadata:
  labels:
    name: sonar
  name: sonar
spec:
  type: ClusterIpP
  ports:
    - port: 8500
      targetPort: 9000
      name: sonarport
  selector:
    name: sonar
